export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  VERIFY_REQUEST: "VERIFY_REQUEST",
  VERIFY_SUCCESS: "VERIFY_SUCCESS",
  VERIFY_FAILURE: "VERIFY_FAILURE",
};

export const userContants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
};

export const initialDataConstants = {
  GET_ALL_INITIAL_DATA_REQUEST: "GET_ALL_INITIAL_DATA_REQUEST",
  GET_ALL_INITIAL_DATA_SUCCESS: "GET_ALL_INITIAL_DATA_SUCCESS",
  GET_ALL_INITIAL_DATA_FAILURE: "GET_ALL_INITIAL_DATA_FAILURE",
};

export const cartConstants = {
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",

  OPEN_CART_REQUEST: "OPEN_CART_REQUEST",
  OPEN_CART_SUCCESS: "OPEN_CART_SUCCESS",
  OPEN_CART_FAILURE: "OPEN_CART_FAILURE",

  RESET_CART: "RESET_CART",

  REMOVE_TO_CART_REQUEST: "REMOVE_TO_CART_REQUEST",
  REMOVE_TO_CART_SUCCESS: "REMOVE_TO_CART_SUCCESS",
  REMOVE_TO_CART_FAILURE: "REMOVE_TO_CART_FAILURE",
  GET_ALL_CART_ITEM_REQUEST: "GET_ALL_CART_ITEM_REQUEST",
  GET_ALL_CART_ITEM_SUCCESS: "GET_ALL_CART_ITEM_SUCCESS",
  GET_ALL_CART_ITEM_FAILURE: "GET_ALL_CART_ITEM_FAILURE",

  INCREASE_CART_QTY_REQUEST: "INCREASE_CART_QTY_REQUEST",
  INCREASE_CART_QTY_SUCCESS: "INCREASE_CART_QTY_SUCCESS",
  INCREASE_CART_QTY_FAILURE: "INCREASE_CART_QTY_FAILURE",
  DECREASE_CART_QTY_REQUEST: "DECREASE_CART_QTY_REQUEST",
  DECREASE_CART_QTY_SUCCESS: "DECREASE_CART_QTY_SUCCESS",
  DECREASE_CART_QTY_FAILURE: "DECREASE_CART_QTY_FAILURE",
};



export const brandProductConstants = {
  GET_ALL_BRANDPRODUCTS_REQUEST: "GET_ALL_BRANDPRODUCTS_REQUEST",
  GET_ALL_BRANDPRODUCTS_SUCCESS: "GET_ALL_BRANDPRODUCTS_SUCCESS",
  GET_ALL_PBRANDRODUCTS_FAILURE: "GET_ALL_BRANDPRODUCTS_FAILURE"
};

export const productConstants = {
  GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_CATPRODUCTS_SUCCESS: "GET_ALL_CATPRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",

  GET_PRODUCT_DETAILS_REQUEST: "GET_PRODUCT_DETAILS_REQUEST",
  GET_PRODUCT_DETAILS_SUCCESS: "GET_PRODUCT_DETAILS_SUCCESS",
  GET_PRODUCT_DETAILS_FAILURE: "GET_PRODUCT_DETAILS_FAILURE",

  GET_ALL_PRODUCTS_QTY_REQUEST: "GET_ALL_PRODUCTS_QTY_REQUEST",
  GET_ALL_PRODUCTS_QTY_SUCCESS: "GET_ALL_PRODUCTS_QTY_SUCCESS",
  GET_ALL_PRODUCTS_QTY_FAILURE: "GET_ALL_PRODUCTS_QTY_FAILURE",

  GET_PRODUCT_BY_SLUG_REQUEST: "GET_PRODUCT_BY_SLUG_REQUEST",
  GET_PRODUCT_BY_SLUG_SUCCESS: "GET_PRODUCT_BY_SLUG_SUCCESS",
  GET_PRODUCT_BY_SLUG_FAILURE: "GET_PRODUCT_BY_SLUG_FAILURE",
  GET_PRODUCT_BY_ID_REQUEST: "GET_PRODUCT_BY_ID_REQUEST",
  GET_PRODUCT_BY_ID_SUCCESS: "GET_PRODUCT_BY_ID_SUCCESS",
  GET_PRODUCT_BY_ID_FAILURE: "GET_PRODUCT_BY_ID_FAILURE",
  GET_PRODUCT_BY_BRAND_ID_REQUEST: "GET_PRODUCT_BY_BRAND_ID_REQUEST",
  GET_PRODUCT_BY_BRAND_ID_SUCCESS: "GET_PRODUCT_BY_BRAND_ID_SUCCESS",
  GET_PRODUCT_BY_BRAND_ID_FAILURE: "GET_PRODUCT_BY_BRAND_ID_FAILURE",
  GET_PRODUCT_FILTER_BY_ID_REQUEST: "GET_PRODUCT_FILTER_BY_ID_REQUEST",
  GET_PRODUCT_FILTER_BY_ID_SUCCESS: "GET_PRODUCT_FILTER_BY_ID_SUCCESS",
  GET_PRODUCT_FILTER_BY_ID_FAILURE: "GET_PRODUCT_FILTER_BY_ID_FAILURE",
  GET_PRODUCT_BY_PRICE_REQUEST: "GET_PRODUCT_BY_PRICE_REQUEST",
  GET_PRODUCT_BY_PRICE_SUCCESS: "GET_PRODUCT_BY_PRICE_SUCCESS",
  GET_PRODUCT_BY_PRICE_FAILURE: "GET_PRODUCT_BY_PRICE_FAILURE",
};



export const SearchConstants = {
  GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",

  GET_PRODUCT_DETAILS_REQUEST: "GET_PRODUCT_DETAILS_REQUEST",
  GET_PRODUCT_DETAILS_SUCCESS: "GET_PRODUCT_DETAILS_SUCCESS",
  GET_PRODUCT_DETAILS_FAILURE: "GET_PRODUCT_DETAILS_FAILURE",

  GET_ALL_PRODUCTS_QTY_REQUEST: "GET_ALL_PRODUCTS_QTY_REQUEST",
  GET_ALL_PRODUCTS_QTY_SUCCESS: "GET_ALL_PRODUCTS_QTY_SUCCESS",
  GET_ALL_PRODUCTS_QTY_FAILURE: "GET_ALL_PRODUCTS_QTY_FAILURE",

  GET_PRODUCT_BY_SLUG_REQUEST: "GET_PRODUCT_BY_SLUG_REQUEST",
  GET_PRODUCT_BY_SLUG_SUCCESS: "GET_PRODUCT_BY_SLUG_SUCCESS",
  GET_PRODUCT_BY_SLUG_FAILURE: "GET_PRODUCT_BY_SLUG_FAILURE",
  GET_PRODUCT_BY_ID_REQUEST: "GET_PRODUCT_BY_ID_REQUEST",
  GET_PRODUCT_BY_ID_SUCCESS: "GET_PRODUCT_BY_ID_SUCCESS",
  GET_PRODUCT_BY_ID_FAILURE: "GET_PRODUCT_BY_ID_FAILURE",
  GET_PRODUCT_BY_BRAND_ID_REQUEST: "GET_PRODUCT_BY_BRAND_ID_REQUEST",
  GET_PRODUCT_BY_BRAND_ID_SUCCESS: "GET_PRODUCT_BY_BRAND_ID_SUCCESS",
  GET_PRODUCT_BY_BRAND_ID_FAILURE: "GET_PRODUCT_BY_BRAND_ID_FAILURE",
  GET_PRODUCT_FILTER_BY_ID_REQUEST: "GET_PRODUCT_FILTER_BY_ID_REQUEST",
  GET_PRODUCT_FILTER_BY_ID_SUCCESS: "GET_PRODUCT_FILTER_BY_ID_SUCCESS",
  GET_PRODUCT_FILTER_BY_ID_FAILURE: "GET_PRODUCT_FILTER_BY_ID_FAILURE",
  GET_PRODUCT_BY_PRICE_REQUEST: "GET_PRODUCT_BY_PRICE_REQUEST",
  GET_PRODUCT_BY_PRICE_SUCCESS: "GET_PRODUCT_BY_PRICE_SUCCESS",
  GET_PRODUCT_BY_PRICE_FAILURE: "GET_PRODUCT_BY_PRICE_FAILURE",
};



export const reviewConstants = {
  GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",

  GET_PRODUCT_DETAILS_REQUEST: "GET_PRODUCT_DETAILS_REQUEST",
  GET_PRODUCT_DETAILS_SUCCESS: "GET_PRODUCT_DETAILS_SUCCESS",
  GET_PRODUCT_DETAILS_FAILURE: "GET_PRODUCT_DETAILS_FAILURE",

  GET_ALL_PRODUCTS_QTY_REQUEST: "GET_ALL_PRODUCTS_QTY_REQUEST",
  GET_ALL_PRODUCTS_QTY_SUCCESS: "GET_ALL_PRODUCTS_QTY_SUCCESS",
  GET_ALL_PRODUCTS_QTY_FAILURE: "GET_ALL_PRODUCTS_QTY_FAILURE",

  GET_PRODUCT_BY_SLUG_REQUEST: "GET_PRODUCT_BY_SLUG_REQUEST",
  GET_PRODUCT_BY_SLUG_SUCCESS: "GET_PRODUCT_BY_SLUG_SUCCESS",
  GET_PRODUCT_BY_SLUG_FAILURE: "GET_PRODUCT_BY_SLUG_FAILURE",
  GET_PRODUCT_BY_ID_REQUEST: "GET_PRODUCT_BY_ID_REQUEST",
  GET_PRODUCT_BY_ID_SUCCESS: "GET_PRODUCT_BY_ID_SUCCESS",
  GET_PRODUCT_BY_ID_FAILURE: "GET_PRODUCT_BY_ID_FAILURE",
  GET_PRODUCT_BY_BRAND_ID_REQUEST: "GET_PRODUCT_BY_BRAND_ID_REQUEST",
  GET_PRODUCT_BY_BRAND_ID_SUCCESS: "GET_PRODUCT_BY_BRAND_ID_SUCCESS",
  GET_PRODUCT_BY_BRAND_ID_FAILURE: "GET_PRODUCT_BY_BRAND_ID_FAILURE",
  GET_PRODUCT_FILTER_BY_ID_REQUEST: "GET_PRODUCT_FILTER_BY_ID_REQUEST",
  GET_PRODUCT_FILTER_BY_ID_SUCCESS: "GET_PRODUCT_FILTER_BY_ID_SUCCESS",
  GET_PRODUCT_FILTER_BY_ID_FAILURE: "GET_PRODUCT_FILTER_BY_ID_FAILURE",
  GET_PRODUCT_BY_PRICE_REQUEST: "GET_PRODUCT_BY_PRICE_REQUEST",
  GET_PRODUCT_BY_PRICE_SUCCESS: "GET_PRODUCT_BY_PRICE_SUCCESS",
  GET_PRODUCT_BY_PRICE_FAILURE: "GET_PRODUCT_BY_PRICE_FAILURE",
};

export const categoryConstansts = {
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
  GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
};

export const brandConstansts = {
  GET_ALL_BRANDS_SUCCESS: "GET_ALL_BRANDS_SUCCESS",
  GET_ALL_BRANDS_REQUEST: "GET_ALL_BRANDS_REQUEST",
  GET_ALL_BRANDS_FAILURE: "GET_ALL_BRANDS_FAILURE",
};

export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";
export const ADD_TO_CART = "ADD_TO_CART";
export const FILTER_PRODUCTS_BY_SIZE = "FILTER_PRODUCTS_BY_SIZE";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CREATE_ORDER = "CREATE_ORDER";
export const CLEAR_ORDER = "CLEAR_ORDER";
export const CLEAR_CART = "CLEAR_CART";
export const FETCH_ORDERS = "FETCH_ORDERS";

export const pageConstants = {
  CREATE_PAGE_REQUEST: "CREATE_PAGE_REQUEST",
  CREATE_PAGE_SUCCESS: "CREATE_PAGE_SUCCESS",
  CREATE_PAGE_FAILURE: "CREATE_PAGE_FAILURE",
};
